### ISSUE TITLE
Is it possible to apply group membership when authenticating a user with django-mama-cas and django-cas-ng?

### ISSUE THREAD

**Issue by pylonsarenice** [jbittel/django-mama-cas#71]
I am using django-mama-cas (2.4.0) and django-cas-ng (3.5.10) to manage user authorisation (single sign on, single log off, group membership) across a few django (1.11) projects. I am able to apply user attributes (first_name, last_name, email address) from the cas server to the cas-ng clients using the callback 'mama_cas.callbacks.user_name_attributes' in mama-cas and setting CAS_APPLY_ATTRIBUTES_TO_USER = True on my cas-ng clients.

On my mama-cas server, I also add the user to a number of groups (snippet below) which I want to then apply to the users on the cas-ng clients.

```
group = Group.objects.get(name=groupname)
user.groups.add(group)
```

However, when I try using the callback 'mama_cas.callbacks.user_model_attributes' in mama-cas none of the group memberships are applied to my clients (I check this via the admin interface and via the django shell).

Is applying group membership from mama-cas to cas-ng possible or am I doing something wrong? If it's not possible my next best idea was to create some boolean custom user attributes, i.e. user.is_member_groupA etc but would welcome advice.

Thanks in advance!

(This is a cross-post from https://stackoverflow.com/questions/52840298/is-it-possible-to-apply-group-membership-when-authenticating-a-user-with-django - I am not sure what the etiquette is but I can copy answers across etc)

Update 1:
From the callbacks.py I see that only fields within user._meta_fields are added to the dict of attributes returned and that user.groups etc are not included here. From this I presume that group memberships are not intended to be applied from mama-cas to cas-ng as I am trying?

**Comment by stephane** [comment]
You can provide your own callback.
https://django-mama-cas.readthedocs.io/en/latest/settings.html#django.conf.settings.MAMA_CAS_SERVICES

**Comment by pylonsarenice** [comment]
Thank you Stephane. In the meantime I created a custom user model with additional Boolean fields indicating group membership.

**Comment by ernest1914** [comment]
For posterity:

If you're using a virtual environment, you can find and edit the callbacks.py somewhere similiar to _lib/python3.10/site-packages/mama_cas_.

You can access the attributes returned by the custom functions in callbacks.py through _request.session['attributes']_ . 

If someone can leave a link to official docs describing these, it would be appreciated, because I just found out about these by mere chance.

In my case, I also just created a custom user model with a groups or permissions field in django-mama-cas server then accessed the values in the django-cas-ng client through request.session['attributes']. Although I feel like there's a better solution out there.
